### ISSUE TITLE
No module named 'facelib'

### ISSUE THREAD

**Issue by KittenYang** [ashleykleynhans/runpod-worker-inswapper#1]
When I run `python3 swapper.py` it just give me error below: 
```
Traceback (most recent call last):
  File "/workspace/inswapper/swapper.py", line 131, in <module>
    from restoration import *
  File "/workspace/inswapper/restoration.py", line 12, in <module>
    from facelib.utils.face_restoration_helper import FaceRestoreHelper
ModuleNotFoundError: No module named 'facelib'
```

**Comment by ashleykleynhans** [comment]
Was your venv activated and did you run swapper.py from within the `/workspace/inswapper` directory?

**Comment by KittenYang** [comment]
@ashleykleynhans yes, for sure

**Comment by ashleykleynhans** [comment]
Strange, I tested setting it up from scratch on a new pod and it worked fine.

**Comment by KittenYang** [comment]
@ashleykleynhans what's your RunPod instance spec?

**Comment by ashleykleynhans** [comment]
@KittenYang I mount my Network Volume to an A5000, but the instance type should not really matter, are you perhaps on the RunPod Discord?  You can look for me there (ashleyk) and send me a DM and then maybe we can do a Discord call and try to solve the issue.

**Comment by ashleykleynhans** [comment]
Also are you looking to run this in Serverless or in GPU Cloud?  This one is designed specifically for Serverless, if you are looking at running it in GPU Cloud, you should rather use https://github.com/haofanwang/inswapper .

**Comment by KittenYang** [comment]
btw,this repo has better result than codeformer, can you make this repo to RunPod serverless API instead of Gradio GUI? https://github.com/harisreedhar/Swap-Mukham

**Comment by ashleykleynhans** [comment]
Thanks, I will check it out

**Comment by ashleykleynhans** [comment]
@KittenYang I tried out Swap-Mukham and the results are MUCH worse than I am getting here, what settings did you use to get good results?

**Comment by KittenYang** [comment]
@ashleykleynhans 1. Open face parsing 2. select GFPGAN 3. Open advanced mask

**Comment by ashleykleynhans** [comment]
@KittenYang It still gives me worse results than this.  I tried several different combinations of settings and every single one of them was worse than this.  Please send me images to show me an image from this application as well as Swap Mukham so I can compare your results with the ones I am getting?

**Comment by KittenYang** [comment]
> Also are you looking to run this in Serverless or in GPU Cloud? This one is designed specifically for Serverless, if you are looking at running it in GPU Cloud, you should rather use https://github.com/haofanwang/inswapper .

Finally I run this. But got new problem, cause this method `result_image = face_swap(source_image_path, target_image_path)` is so slow and may queued a long time, this could lead to a high likelihood of API requests timing out, resulting in the loss of inference image results. How can I solve this problem?

**Comment by ashleykleynhans** [comment]
@KittenYang  The `face_swap` function is usually pretty quick, its usually the CodeFormer `face_restoration` function that is slow.  How large is the image that you're trying to do a face swap on and which GPU type are you using in RunPod?

**Comment by KittenYang** [comment]
@ashleykleynhans A5000，i set the idel time to 5s, so each request need to cold start the docker. Get this error:
```

Traceback (most recent call last):
  File "/api_run2.py", line 46, in <module>
    r = requests.post(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.runpod.ai', port=443): Max retries exceeded with url: /v2/xxxx/runsync (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

```

**Comment by ashleykleynhans** [comment]
Are you trying to run those code in GPU cloud? 
This application is designed to work in Serverless only, not in GPU cloud.
If you want something for GPU cloud, look at this one instead, and add HTTP port 5000 to your pod so that you can connect to it externally:

https://github.com/ashleykleynhans/inswapper-flask-api

**Comment by KittenYang** [comment]
got the new error 😂
```
2023-08-20T15:23:59.161978669Z Worker Initiated
2023-08-20T15:23:59.161999833Z Symlinking files from Network Volume
2023-08-20T15:23:59.163663828Z ln: failed to create symbolic link '/workspace': File exists
2023-08-20T15:23:59.172916940Z Starting RunPod Handler
2023-08-20T15:23:59.172987462Z /start.sh: line 16: /workspace/runpod-worker-inswapper/venv/bin/activate: No such file or directory
2023-08-20T15:23:59.173003462Z /start.sh: line 17: cd: /workspace/runpod-worker-inswapper: No such file or directory
2023-08-20T15:23:59.173425793Z /start.sh: line 18: python: command not found
```

**Comment by ashleykleynhans** [comment]
@KittenYang Did you build it for Network Volume?  Build it for Stand-alone without Network Volume instead.

**Comment by KittenYang** [comment]
@ashleykleynhans but the total docker images has 8G+ size, and once I change `rp_handler.py` code I need to rebuild the docker. Besides, every job needs to download the whole docker. It takes long time. Does the download initializing period count for cost?

**Comment by ashleykleynhans** [comment]
You are not billed for Docker image pulls in Serverless, only in GPU cloud, and the images are not pulled for every request, they are only deployed each time you increment the docker image tag version within your RunPod template, or if you increase your number of max workers.  Its currently better not to use Network volumes for this because the models are not very large and RunPod also has limited availability of GPUs in the regions that have network volumes available.

**Comment by KittenYang** [comment]
@ashleykleynhans Thanks dude!
