### ISSUE TITLE
Certainly! If you're reporting this issue on GitHub, you might consider writing something like the following:  Issue Description:  I encountered an issue while using the face-swapping application. Here are the details of the problem:

### ISSUE THREAD

**Issue by rahilparsana** [ashleykleynhans/runpod-worker-inswapper#2]
Traceback (most recent call last):
  File "/workspace/runpod-worker-inswapper/rp_handler.py", line 364, in face_swap_api
    result_image = face_swap(
  File "/workspace/runpod-worker-inswapper/rp_handler.py", line 235, in face_swap
    source_img = [Image.open(img_path) for img_path in source_img_paths]
  File "/workspace/runpod-worker-inswapper/rp_handler.py", line 235, in <listcomp>
    source_img = [Image.open(img_path) for img_path in source_img_paths]
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3305, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/inswapper/source_396c69b6-7fab-4e0a-b935-52fd6fed080c.png'

**Comment by ashleykleynhans** [comment]
There is a problem with the source image, works fine for me.

**Comment by rahilparsana** [comment]
I'm using base64-encoded JPEG images in the API, and the code is deployed in a serverless RunPod environment with the Docker image ashleykza/runpod-worker-inswapper:standalone-1.2.2

**Comment by ashleykleynhans** [comment]
I have used this on thousands of images and its fine, your image is broken END OF, please stop wasting my time.
