### ISSUE TITLE
Seems that it is running on CPU instead of GPU on runpod

### ISSUE THREAD

**Issue by romansitina** [ashleykleynhans/runpod-worker-inswapper#3]
Hello Ashley, 

First, thank you for your contribution to AI world!

I tried to run your docker image on Runpod.io and from the logs it looks like it is running on CPU. Is this expected?

```
2024-01-18 17:04:27.540
[xzez83263reggo]
[info]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}

```

**Comment by ashleykleynhans** [comment]
Yes it does the face swap on CPU and the upscaling on GPU.    This code is based on inswapper, please log an issue there if you don't like it: https://github.com/haofanwang/inswapper/issues

**Comment by romansitina** [comment]
Thank you.

In their documentation they write

You have to install onnxruntime-gpu manually to enable GPU inference,
install onnxruntime by default to use CPU only inference.

in your requirements.txt there's only onnxruntime - could this be the
problem?
